version: "3"
networks:
  dinky_net:
    external: true
services:
  dinky14:
    restart: always
    image: dinky-test:flink-1.14
    environment:
      - DB_ACTIVE=mysql
      - MYSQL_ADDR=mysql:3306
      - MYSQL_DATABASE=dinky
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=dinky
    networks:
      - dinky_net
