spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # redis 运行模式，standalone ，embedded
    mode: embedded
    database: 8
    redisson:
      # 单节点配置
      singleServerConfig:
        # 连接空闲超时，单位：毫秒
        idleConnectionTimeout: 10000
        # 连接超时，单位：毫秒
        connectTimeout: 10000
        # 命令等待超时，单位：毫秒
        timeout: 3000
        # 命令失败重试次数,如果尝试达到 retryAttempts（命令失败重试次数） 仍然不能将命令发送至某个指定的节点时，将抛出错误。
        # 如果尝试在此限制之内发送成功，则开始启用 timeout（命令等待超时） 计时。
        retryAttempts: 3
        # 命令重试发送时间间隔，单位：毫秒
        retryInterval: 1500
        # 密码
        password:
        # 客户端名称
        clientName: dinky-redis
        # 单个连接最大订阅数量
        subscriptionsPerConnection: 5
        # 节点地址
        address: redis://${spring.redis.host}:${spring.redis.port}
        # 发布和订阅连接的最小空闲连接数
        subscriptionConnectionMinimumIdleSize: 1
        # 发布和订阅连接池大小
        subscriptionConnectionPoolSize: 50
        # 最小空闲连接数
        connectionMinimumIdleSize: 5
        # 连接池大小
        connectionPoolSize: 10
        # 数据库编号
        database: ${spring.redis.database}
        # DNS监测时间间隔，单位：毫秒
        dnsMonitoringInterval: 5000
        # 传输模式
      transportMode: "NIO"
