version: "3"
networks:
  dinky_net:
    external: true
services:
  python-script:
    image: python:3.8
    volumes:
      - ./:/app
    working_dir: /app
    command: 'pip install  -r requirements.txt &&  python main.py dinky14:8888'
    networks:
      - dinky_net
